# Generated by Django 5.1 on 2024-12-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_van_nghe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventprogram',
            name='status',
            field=models.CharField(choices=[('planned', 'Lên kế hoạch'), ('ongoing', 'Đang diễn ra'), ('completed', 'Kết thúc')], default='planned', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(),
        ),
    ]
